### ISSUE TITLE
Proposal（第一次作业，程序改错&简易网络学堂）

### ISSUE THREAD

**Issue by UNIDY2002** [JianGuanTHU/UOJ_Offline#1]
如下。

**Comment by UNIDY2002** [comment]
# 题目描述

（本题是代码改错，目测难度不会大）

小明学习了oop的课程后，跃跃欲试，打算亲手实践一下。

小明希望实现的功能有：

……（见后面的`main.cpp`）

然而，小明遇到了一些bug，怎么都de不掉。于是，他请你来帮他完善他的程序……

## Code

### `main.cpp`

（小明希望实现的大致长这样）

```cpp
#include "my_lib.h"

using namespace std;

int main() {
    string hello = "Hello, world!";
    print(hello);
    print();
    print(2333);
    print(233 > 666);
    print("================");

    auto s = input();
    print(s);
    for (auto c:s) print(c);
    print("================");

    Array a;
    a.add(4);
    a.add(2);
    a.add(7);
    a.cut();
    a.add(5);
    print(a.getSize());
    print(a);
    return 0;
}
```

### `my_lib.h`

（这道题暂时不想分离出`my_lib.cpp`……）

**解题者可以修改的部分是`my_lib.h`。**

会设置一些错误：

- `void print(std::string s = "") `（与`void print()`冲突）
- 漏掉`void print(const char *s)`（这会让`print("================")`产生意外结果）
- `auto`用错一处
- 自定义类型的访问权限问题
- 个别地方忘了注明`Array::`或者`std::`

emm目前先想到这么些问题。

# 考察点

- 函数重载（隐式类型转换、缺省值的不当使用）
- auto
- 自定义类型的易错点

**Comment by UNIDY2002** [comment]
# 题目描述

~~Json是一种……的语言，它广泛运用于……~~

学习了oop的基本知识后，请你也试着做一个 **（简化版的）** Json解析工具。

## 任务要求

从输入得到一个Json字符串，解析得到相应的Json类后，会进一步进行一些查询，例如：

- Json元素的类型
- Json元素的数据
- Json列表的长度
- （好像也没别的可查的了）

## 问题简化与约定

作为一次课后作业，必然无法要求真正地解析Json，而且才学了一点点类的知识 ~~（况且重复造轮子也毫无意义）~~ 。因此，对问题进行如下简化：

- 所有字段的数据类型均为**字符串**
- 符号之间留下适当的空白符，**确保可以用cin来简化读入**
- 列表和字典的**长度有限**（比如≤10），实现时用普通静态数组即可（当然不禁止用vector和map）
- 保证**输入合法**，且没有奇怪的输入
- 不对代码的oop程度提过高要求
- ……

## 输入样例

### Json

```json
{
    "animals" : {
        "dog" : [
            {
                "name" : "Rufus" ,
                "age" : "15"
            } ,
            {
                "name" : "Marty" ,
                "age" : "12"
            }
        ]
    }
}
```

### `main.cpp`（部分）

```cpp
Json o = getJson();  // Read from stdin

cout << o.getType() << endl;
assert(o.getType() == "object" && o.contains("animals"));

Json p = o.getObject("animals");
cout << p.getType() << endl;
assert(p.getType() == "object" && p.contains("dog"));

Json q = p.getObject("dog");
cout << q.getType() << endl;
cout << q.getLength() << endl;
assert(q.getType() == "array" && q.getLength() > 1);

Json r = q.getArray(1);
cout << r.getType() << endl;
assert(r.getType() == "object" && r.contains("age"));

Json s = r.getObject("age");
cout << s.getType() << endl;
assert(s.getType() == "string");

cout << s.getString() << endl;
```

# 考察点

- 类的基本操作
- ~~C++语法（递归）~~

**Comment by liangrz15** [comment]
第一题不错，后期需要明确题目中的考点。
第二题有一定的算法难度，会导致同学们关注于算法的设计而非OOP的基础知识。建议更换这一道题，可参考第一次作业**电子签到统计系统**的难度。
如果能合理修改或更换第二道题，可以替代作业。

**Comment by UNIDY2002** [comment]
~~（我后来也发现Json那题有点问题……[捂脸]）~~

# 题目描述

网络学堂在清华信息化进程中扮演着重要的角色，任何一位清华学子都离不开网络学堂。

学习了OOP的基础知识后，请你也设计一个简易的网络学堂，能够添加事项，并进行查找和输出等操作。

## 任务要求

众所周知，网络学堂由多门课程组成，每门课又有作业、公告、文件、讨论和答疑等模块。

为简化问题，在本题中，**你只需实现作业和文件两个模块**。

我们认为，一个文件最关键的要素是名称和文件类型，而一项作业最关键的要素则就是名称和ddl。在本题中，**我们用一个正整数来代替ddl**。

（此处略去对需求的描述，可见后面的`main.cpp`。）

## 约定

- 课程数量、每门课的作业数量和每门课的文件数量**均不超过10**。
- 在每门课程中，**不存在同名的作业，也不存在同名的文件**。
- 我们的测试顺序是：添加作业或文件→查找作业或文件→批量输出单门课程中的作业或文件→将课程添加到网络学堂→批量输出网络学堂中的全部作业和文件。因此，**不存在从网络学堂中获取某门课程后再对课程进行操作的要求**。（这一约定是考虑到没有系统地学过引用和指针。）
- ……

## 输入样例

### `main.cpp`（部分）

```cpp
Course oop;
oop.addHomework("hw1", 2);
oop.addFile("week1", "pptx");
oop.addHomework("hw2", 4);
cout << oop.findHomework("hw1") << endl;
oop.printHomework();

Course physics;
physics.addFile("syllabus", "pdf");

Learn learn;
learn.addCourse(oop);
learn.addCourse(physics);
learn.print();
```

## 输出格式

（此处略）


# 考察点

- 类的基本操作

**Comment by liangrz15** [comment]
修改后的两道题都不错，可以替代一次作业。
第一题最好能尽量地覆盖重要的知识点。
之后需要完成题面、数据、标答和judger。
