### ISSUE TITLE
Proposal (第5次作业 Register)

### ISSUE THREAD

**Issue by NickLennonLiu** [JianGuanTHU/UOJ_Offline#11]
# 第五次作业 Register

## 题目描述

开发网站的时候，服务器处理用户传来的数据时需要有足够的鲁棒性，其中就包括对数据格式的检查。现在从网站前端传来了包含用户注册帐号时提交信息的字符串，请你完成后端检验代码，如果存在非法格式的数据，则输出报错信息；如果注册信息合法，则在屏蔽掉私密信息后输出注册信息。

### 格式要求

用户名username：长度4 - 15，由字母或数字或下划线_构成，且首字符必须为字母

密码password：长度8-20，为字母和数字的组合，且二者必须都有。

邮箱email:  本题只考虑满足正则表达式([\w]+@[\w\.]+)的邮箱为合法邮箱地址。

## 输入数据

输入一行简单的json格式的字符串：字符串首尾为'{'、'}'，内部以 "键" : "值" 的格式记录信息。键和值中不会出现 " 和 : 。不同的键值对之间使用 , 进行分隔。需要注意双引号之外可能存在多余的空格。题目保证在输入数据在json格式上不会出错。

### 样例

```json
{"username":"wrongpass", "password":"abc", "email":"example@qq.com"}
```

```json
{"username": "twoillegal?", "email": "test.thu.com", "password": "abc12345"}
```

```json
{"password" : "abc12345", "username": "correct", "email": "a@b.c.com"}
```

## 输出要求

- 数据合法时：

用户名：保留开头三个字符，后续字符用*代替

密码：所有字符用*代替

邮箱：除了@与.外的其他字符用*代替。

- 数据不合法时：

根据三个字段的非法情况输出"Illegal [username],[password],[email]"

（由于后端只需要检验数据格式的合法性，因此不需要返回具体的错误原因）

### 样例

对应”输入数据“部分三个样例的输出：

```
Illegal password
```

解释：密码长度过短

```
Illegal username,email
```

解释：用户名中包含除了字母和密码以外的特殊字符?，邮箱不符合题给正则表达式（不含@）

```
Successfully registered.
username: cor****
password: ********
email: *@*.*.***
```

## 提交要求

提交一个main.cpp，完成上述要求。

## 考察点

STL、regex

**Comment by hzhwcmhf** [comment]
挺好的。请编写标程、输入输出数据、judger，测试通过后发到邮箱 huangfei382@163.com

**Comment by hzhwcmhf** [comment]
验收通过
