### ISSUE TITLE
Proposal（第5次作业 简易爬虫)

### ISSUE THREAD

**Issue by Ksitta** [JianGuanTHU/UOJ_Offline#13]
# 简易爬虫

众所周知，大一的小学期里大家就要自己写网页爬虫了，那么不如我们提前来熟悉一下正则表达式的使用。

我们需要将网页中的有效信息提取出来

以html网页文档中如下一段代码为例

\<span class="abc" id="xxx"\>text\</span\>

span作为一个标签，class一般用于CSS样式相同的模块，统一设置其样式，精简代码。你可以理解为同一个class就是同一类的东西，我们需要编写一个正则表达式实现如下匹配

给定任意一个标签xxx，以及一个样式yyy，我们要把所有满足条件的代码块中的text部分提取出来，并输出，如果不满足则输出not found。
额外要求：输出至指定ostream

### 输入格式

第一行标签名称

第二行样式名称

第三行 一个整数m表示后续有m行输入

比如如下输入

```
div
new
4
<div class="new" id="qwe">hello</span>
<div id="aaa" class="new">hello1</span>
<span class="new">hello2</span>
<div id="new" class="hahaha">hello3</span>
```

### 输出结果

```
hello
hello1
not found
not found
```

会提供一个用于处理输入的main.cpp

需要同学们实现的是一个类，以及findText()函数，每次将输出内容传给传入的ostream

```
class Match{
public:
    Match(string label, string classname, ostream & out){
    
    }
    void findText();
    
};
```

### 考察内容：

流输出对象
正则表达式

**Comment by hzhwcmhf** [comment]
有几个问题
1. Match这个构造函数不太常规，一般来说，不会把输出流当做类的变量，而是将查询的结果通过函数返回值传递回去。从目前的题目来看，流输出好像只考察了out不能复制。
2. 正则表达式部分好像没说清楚，标签具体满足怎样的格式？标签中可能存在任意多的属性，我们只需要看"class"？
3. 样例有点问题，div开头的用span做了结尾
4. 我有点没弄清楚这题想让同学们怎么做，是写一个正则表达式抽取出 标签（div）  class的值  和有效信息，然后再比对是否满足匹配的条件，决定是否输出有效信息？

**Comment by Ksitta** [comment]
> 有几个问题
>
> 1. Match这个构造函数不太常规，一般来说，不会把输出流当做类的变量，而是将查询的结果通过函数返回值传递回去。从目前的题目来看，流输出好像只考察了out不能复制。
> 2. 正则表达式部分好像没说清楚，标签具体满足怎样的格式？标签中可能存在任意多的属性，我们只需要看"class"？
> 3. 样例有点问题，div开头的用span做了结尾
> 4. 我有点没弄清楚这题想让同学们怎么做，是写一个正则表达式抽取出 标签（div）  class的值  和有效信息，然后再比对是否满足匹配的条件，决定是否输出有效信息？

稍微修改了一下题面

**1.这里考虑出现失误了**
重写为下列形式

不再考察ostream，考察一下stl::list吧，主要是利用卡时间（卡数组向前移动）和卡内存（动态增删，让用数组而不删除的同学内存超出）来让同学们用链表

主要在于考察正则表达式，并且需要匹配两次（因为一次正则匹配直接得到的话处理起来会比较麻烦），如果链表这里不太合适可以再修改一下

构造一个Match类，需要实现以下部分

```c++
class Match{
private:
	
public:
    Match(string label, string classname){
    
    }
    void add_text(string s); // 如果传入的s满足匹配，那么添加进去
    string get_text();       // 获取第一个字符串，并移除
    int size();              // 还有多少个字符串
};
```

调用add_text增加一个

**2.格式**

```
<标签 属性1="xxx" 属性2="xxx" 属性3="xxx">内容</标签>
```

可能有**任意多个标签**，但是只有**1个或者0个class**
**标签、属性之间以空格分隔**

内容部分可能包含空格，其他部分不含有多余的空格

- 如果标签满足条件，但样式（class）不存在或者不满足条件，那么就输出Not satisfied
- 如果标签满足条件，且样式满足条件，那么输出其中的内容部分
- 如果标签不满足条件，那么不做处理

输入样例

```
div
new
5
<div class="new" id="qwe">hello</div>
<div id="aaa" class="new">hello1</div>
<span class="new">hello2</span>
<div id="new" class="hahaha">hello3</div>
<div id="abc">hello world</div>
```

样例输出

```
hello
hello1
Not satisfied
```

**3.已经修正**
**4.修改后的题面想让同学们做的就是对于一个字符串，先匹配标签，满足条件再匹配class**

**Comment by hzhwcmhf** [comment]
1. 感觉这里用list也不是特别合理，毕竟还是先入先出，和直接输出到屏幕好像没啥区别。我感觉是不是可以考虑：Match只过滤标签，处理文本时按class存着。之后再要求query不同的class，输出包含该class的所有内容。举个例子就是

输入
```
div
5  //这是输入个数
<div class="new" id="qwe">hello</div>
<div id="aaa" class="new">hello1</div>
<span class="new">hello2</span>
<div id="new" class="hahaha">hello3</div>
<div id="abc">hello world</div>
2 //这是查询个数
new
hahaha
```
输出
```
-----new-----
hello
hello1
-----hahaha-----
hello3
```

另外样例出的稍微正经一点吧，辨识度高一点，不要用123标号

4. 我感觉这好像只用一次匹配，因为给定标签后，正则表达式就可以用标签组出来，class的部分留空就可以。类似```<{label}(.*)id="(\w+)"(.*)>(.*)</{label}>```，把label直接替换成输入里给定的label

**Comment by Ksitta** [comment]
既然实现query功能，我觉得就比较像python中的bs4包了，不如直接做一个过滤功能

```c++
class Match{
    string label;
	vector<string> raw_text;
public:
    Match(const string & lab);
    
    void add_raw(const string & str);
        
    Match filter(const string & attr, const string & val);

    vector<string> get_content();
};
```

实现从一个label构造Match对象

add_raw则是传入一个

```
<标签 属性1="xxx" 属性2="xxx" 属性3="xxx">内容</标签>
```

这样的字符串，对于满足label条件（只检查label条件）的放入vector，其他的就丢弃

filter函数传入属性（attr）和值（val）按照 属性="值" 即 attr="val" 来过滤得到一个新的Match对象，新的Match对象则只包含满足过滤条件的串。

get_content()就是返回当前Match对象内的所有串的内容部分

这样可以实现不同属性多次过滤

**Comment by hzhwcmhf** [comment]
如果要仿python，我感觉不如把接口再简化一下，没必要add_raw这么处理。举个例子：

```
vector<string> elements;
auto allmatch = Match(elements);
auto div_elements = allmatch.filterLabel("div");
auto div_new = div_elements.filterAttr("class", "new");
auto div_new2 = Match(elements).filterLabel("div").filterAttr("class", "new");
```
再加一个输出就可以了。

而且比较有意思的是这个可以lazy化，就是filterLabel和filterAttr构造对象的时候并不需要把内容处理一遍，只需要get_content的时候过滤就行。不过这一点可以看你想不想搞吧，如果要考的话可能需要一些卡暴力做法的方法。或者留着，让大家自选暴力做法和lazy方法也行。

**Comment by Ksitta** [comment]
lazy做法这里应该卡哪一个属性我有一点疑惑

这个lazy标记我觉得效果是在于我反复过滤同一个属性
比如

```
div_elements.filterAttr("class", "new").filterAttr("class", "new");
```

如果每次过滤的都是不同的属性

```
div_elements.filterAttr("class", "new").filterAttr("id", "foot");
```

那么实际上懒惰标记效率应该和直接处理区别不太大

或者说是在数组整体拷贝这里可能存在一些区别？
比如用懒惰标记只有在get_content这里存在一个不断向数组添加元素的过程，其他地方全是数组整体拷贝

而暴力做法则是每次构造新的Match对象都会让数组元素一个一个push进去


只考虑filterAttr()

在每次过滤的属性都不同至于匹配次数，应该是相同的

采用lazy标记那么就相当于我需要维护一个attr的字典，每次过滤相当于在里面添加一个新的字段

然后在get_content()的时候对raw_text中的每一项去匹配这个字典里所有项目，如果全部匹配成功则直接放进要返回的数组里面，某一次匹配失败则直接转下一项。总次数是 

$$
\sum_{i=0}^{n}f(raw\_text[i])
$$
f(x)表示x这一条目满足的属性数量

而暴力做法则是每次就只把满足的加进去，每次匹配n条，n为当前match对象的raw_text条目数量，得到的match对象中raw_text条目数量为所有满足该属性的条目数，那么加起来刚好和上面相等。

$$
\sum_{i=0}^{k}g(attr[i])
$$
g(x)表示满足的该属性的条目数量

**Comment by hzhwcmhf** [comment]
确实复杂度是一样的。可能主要省下的是内存，或者说存在构建了filter但没有访问的情况。
现在python包里面这种是用迭代器访问，他的filter过程分摊到了读取过程中，如果只读了前几个的话就不会有那么大的开销。
另外还有可能合并多个标记建索引，这个可能就太复杂了。

这题的话你可以再想想，也不一定非要lazy。但不推荐卡太小的内存，OJ的内存可能不太稳定

**Comment by Ksitta** [comment]
自己实现了一个lazy标记的标程，发现还是有点困难的，因为原本实现这个类就需要写一些代码，感觉比起作业来说难了一些，所以这个作为一个非必要要求让同学们实现吧，就不卡内存了。

### 题目描述

众所周知，大一的小学期里大家就要自己写网页爬虫了，那么不如我们提前来熟悉一下正则表达式的使用。

我们需要将网页中的有效信息提取出来

一个html网页文档中的标签格式如下

```
<标签 属性1="值1" 属性2="xxx" 属性3="xxx">内容</标签>
```

以html网页文档中如下一段代码为例

```html
<span class="new" id="xxx">text</span>
```

span就是一个标签，class一般用于CSS样式相同的模块，统一设置其样式，精简代码。你可以理解为同一个class就是同一类的东西，我们需要编写一个正则表达式实现如下匹配。

给定任意一个标签xxx，以及一组属性yyy，我们要把所有满足条件的代码块中的text部分提取出来。

文件下载地址：[下载链接](/download.php?type=problem&id=101)

你需要做的是，补充完整以下类中各个函数的实现

```c++
class Match{
private:
    
public:
    Match(vector<string> & raw);
    Match filterAttr(const string & attr, const string & val);
    Match filterLabel(const string & lab);
    vector<string> getContent();
};
```

其中我们调用Match(vector\<string> & raw)时会将所有已经输入的原始串传入到这个对象的构造函数，你需要将其存下来。而我们每次调用filterAttr()或者filterLabel()函数时，你需要返回一个满足该次filter条件的Match对象，对返回的这个对象调用getContent()函数时，你需要将所有满足条件的原始串中的text部分存入到一个vector\<string>对象中返回。

例如

我们使用

```html
<div class="new" id="title">This is a title</div>
<div id="header" class="new">hello</div>
<span class="new">world</span>
<span class="new">look</span>
```

这样一组原始串构造了一个Match对象raw

调用raw.filterLabel("div")后返回的**新对象label_div**则应该筛选出以**div**为标签的串

```html
<div class="new" id="title">This is a title</div>
<div id="header" class="new">hello</div>
```

调用label_div.get_content()函数返回的数组中应该只含有

```
This is a title
hello
```

并且我们还可以**继续对label_div对象进行过滤**

如果我们调用label_div.filterAttr("id", "title")得到对象**div_id**，那么应该只剩下

```html
<div class="new" id="title">This is a title</div>
```

满足条件

div_id.getContent()函数返回的数组中应该含有

```
This is a title
```

### 输入样例

第一行包括一个正整数 $n$，表示待匹配的原始串总数。

接下来n行均为以下格式

```html
<标签 属性1="值1" 属性2="xxx" 属性3="xxx">内容</标签>
```

注：

- 一个标签可能含有任意多个属性（可能为0）

- 标签、属性之间以单个空格分隔，没有多余空格，标签、属性、值中**只可能**由英文字母、数字和`-`组成，属性名互不相同。

- 标签中**属性的顺序不固定**

- 内容部分**可能含有**`"`、`-`、数字、英文字母，例如以下输入是合法的

  ```html
  <span class="new" id="title">class="old"</span>
  ```

  这个例子中，内容部分为class=”old“

接下来是一个正整数$m$，表示有$m$组查询，每组查询格式如下

第一行一个正整数$t$和一个字符串$label$

接下来$t$行，每行含有两个字符串，表示属性名和值

如以下一组查询

```
3 div
class new
id title
rel dns
```

就是查询所有标签为div，其中有3组属性满足class="new" id="title" rel="dns"的字符串，例如

```html
<div id="title" class="new" rel="dns">text</div>
```

就是一个符合要求的串。

**样例输入**

```
6
<div class="new" id="title">This is a title</div>
<div id="header" class="new">hello</div>
<span class="new">world</span>
<div id="new" class="fresh">happy</div>
<span>oop</span>
<div class="el-element">class="new"</div>
3
2 div
class new
id title
1 div
class el-element
0 span
```

### 输出样例

按照输入顺序，所有满足条件的筛选所得的内容。

输入输出已经在`main.cpp`中实现好了

```
--- div class="new" id="title" ---
This is a title
--- div class="el-element" ---
class="new"
--- span ---
world
oop
```

### 要求

1. 补充完整`match.h` `match.cpp`
2. （非要求）Match类实现过程中，其实有一种lazy标记的办法，如果你采用暴力做法，即每次都把所有满足条件的串传给新的Match对象，这可能导致很大的内存开销，但是如果能合理利用智能指针(shared_ptr)和lazy标记策略，那么就能节省大量内存空间。

### 限制与约定

$2 \leq n,m \leq 5000$

**时间限制：1s**

**空间限制：256MB**

### 提交格式

根据提供的 `main.cpp` 的内容，补充对应的Match类的代码`match.h` `match.cpp`。你应该将你的文件打包成一个zip压缩包并上传。

### 评分标准

OJ评分占100%

**Comment by hzhwcmhf** [comment]
1. 题面里“例如”这部分最好直接给一个整块的代码，需要解释的地方用注释。现在这版有些承接词看着会比较模糊。
2. 要求第二点，建议说的清楚一点：```Match类实现过程中，如果你每次都把所有满足条件的串传给新的Match对象，这可能导致很大的内存开销。但是你可以使用一种Lazy的方式，即在构造新Match对象时不复制或者过滤串，仅记录filter的需求，最后在get_content中再实现字符串的过滤。```

**Comment by Ksitta** [comment]
修改了这两部分的内容

### 题目描述

众所周知，大一的小学期里大家就要自己写网页爬虫了，那么不如我们提前来熟悉一下正则表达式的使用。

我们需要将网页中的有效信息提取出来

一个html网页文档中的标签格式如下

```
<标签 属性1="值1" 属性2="xxx" 属性3="xxx">内容</标签>
```

以html网页文档中如下一段代码为例

```html
<span class="new" id="header">text</span>
```

span就是一个标签，class、id则是属性，其值分别为new和header，我们需要编写一个由正则表达式实现的类完成如下匹配。

给定任意一个标签label，以及一组属性[attr1="val1", attr2="val2", ......]，我们要把所有满足条件的代码块中的text部分提取出来。

文件下载地址：[下载链接](/download.php?type=problem&id=101)

你需要做的是，补充完整以下类中各个函数的实现

```c++
class Match{
private:
    
public:
    Match(vector<string> & raw);
    Match filterAttr(const string & attr, const string & val);
    Match filterLabel(const string & lab);
    vector<string> getContent();
};
```

其中我们调用Match(vector\<string> & raw)时会将所有已经输入的原始串传入到这个对象的构造函数，你需要将其存下来。

而我们每次调用filterAttr()或者filterLabel()函数时，你需要返回一个满足该次filter条件的Match对象，对返回的这个对象调用getContent()函数时，你需要将所有满足条件的原始串中的text部分存入到一个vector\<string>对象中返回。

例如

```c++
vector<string> raw_text;
raw_text.push_back(R"(<div id="header" class="new">hello</div>)");
raw_text.push_back(R"(<span class="new">world</span>)");
raw_text.push_back(R"(<span>oop</span>)");
Match mat(raw_text); // 现在我们由上面这三条原始数据构造了一个Match对象
auto span_element = mat.filterLabel("span");// 筛选出标签为span的数据
auto content_1 = span_element.getContent(); // 获取这些数据的内容部分
for(auto & c : content_1){
    cout << c << endl;
}
// 这里输出所有满足标签为span的对象
// 期望的输出则是
// world
// oop


// 这里我们继续从标签为span的数据中筛选class="new"的数据
auto span_new = span_element.filterAttr("class", "new");
auto content_2 = span_new.getContent();

for(auto & c : content_2){
    cout << c << endl;
}
// 这里输出所有满足标签为span且属性满足class="new"的对象
// 期望的输出则是
// world
```

### 测试样例

第一行包括一个正整数 $n$，表示待匹配的原始串总数。

接下来n行均为以下格式

```html
<标签 属性1="值1" 属性2="xxx" 属性3="xxx">内容</标签>
```

注：

- 一个标签可能含有任意多个属性（可能为0）

- 标签、属性之间以单个空格分隔，没有多余空格，标签、属性、值中**只可能**由英文字母、数字和`-`组成，属性名互不相同。

- 标签中**属性的顺序不固定**

- 内容部分**可能含有**`"`、`-`、数字、英文字母，例如以下输入是合法的

  ```html
  <span class="new" id="title">class="old"</span>
  ```

  这个例子中，内容部分为class=”old“

接下来是一个正整数$m$，表示有$m$组查询，每组查询格式如下

第一行一个正整数$t$和一个字符串$label$

接下来$t$行，每行含有两个字符串，表示属性名和值

如以下一组查询

```
3 div
class new
id title
rel dns
```

就是查询所有标签为div，其中有3组属性满足class="new" id="title" rel="dns"的字符串，例如

```html
<div id="title" class="new" rel="dns">text</div>
```

就是一个符合要求的串。

**样例输入**

```
6
<div class="new" id="title">This is a title</div>
<div id="header" class="new">hello</div>
<span class="new">world</span>
<div id="new" class="fresh">happy</div>
<span>oop</span>
<div class="el-element">class="new"</div>
3
2 div
class new
id title
1 div
class el-element
0 span
```

**样例输出**

按照输入顺序，所有满足条件的筛选所得的内容。

输入输出已经在`main.cpp`中实现好了

```
--- div class="new" id="title" ---
This is a title
--- div class="el-element" ---
class="new"
--- span ---
world
oop
```

### 要求

1. 补充完整`match.h` `match.cpp` 

2. （非要求）Match类实现过程中，如果你每次都把所有满足条件的串传给新的Match对象，这可能导致很大的内存开销。但是你可以使用一种Lazy的方式，即在构造新Match对象时不复制或者过滤串，仅记录filter的需求，最后在get_content中再实现字符串的过滤。

   - 举个例子，在Match类中增加一个map对象来记录filterAttr需要筛选的标签

     ```c++
     class Match{
         map<string, string> _attr;
     }
     ```

     那么每次增加了新的过滤条件之后就可以直接记录在这个map对象中，而不用反复拷贝原始数据。

     并且这样做还有其他好处，你可以快速判断有没有对**同一个属性**筛选了多个不同的**值**。如果有，那么当然会得到一个空的Match对象。

### 限制与约定

$2 \leq n,m \leq 5000$

**时间限制：1s**

**空间限制：256MB**

### 提交格式

根据提供的 `main.cpp` 的内容，补充对应的Match类的代码`match.h` `match.cpp`。你应该将你的文件打包成一个zip压缩包并上传。

### 评分标准

OJ评分占100%

**Comment by hzhwcmhf** [comment]
可以了。题目出完以后发送题面(markdown格式）、数据、judger、标程到huangfei382@163.com。

**Comment by hzhwcmhf** [comment]
验收通过
