### ISSUE TITLE
Proposal （第二次作业，矩阵运算）

### ISSUE THREAD

**Issue by singlet-Carbene** [JianGuanTHU/UOJ_Offline#14]
#### 知识点

类与对象、函数重载、运算符重载

#### 题目描述

实现一个整数矩阵类Matrix，并通过运算符重载完成矩阵的

1. 数乘 （Matrix * int）
2. 矩阵相加减 (Matrix ± Matrix)
3. 矩阵相乘 (Matrix * Matrix)
4. 下标访问元素(Matrix\[a\]\[b\])
5. 流输入输出 (cin >> Matrix & cout << Matrix)

等功能。

再附加实现求转置的函数transpose()。（求逆和求行列式啥的可能有点难？）

**Comment by hzhwcmhf** [comment]
基本可行，注意几点

1. OOP作业主要目标是设计接口，算法实现不作为主要考点，所以求逆之类的算法可以不用，包括矩阵相乘如果和加减重复也可以只实现一个。
2. matrix[a][b]访问需要有中间对象，这一点课上应该不会讲，所以在题面要有一定提示
3. 矩阵内存的管理看起来比较复杂，需要进一步说明，需要同学们做到什么程度

请细化题面后回复，最好给出样例输入输出

**Comment by singlet-Carbene** [comment]
[题面.md](https://github.com/JianGuanTHU/UOJ_Offline/files/8329649/default.md)

**Comment by singlet-Carbene** [comment]
#### 题目描述

在线性代数中，我们学习了矩阵以及矩阵的一些运算规则。现在你需要完善下面的代码，实现一个整数矩阵类`Matrix`，并实现矩阵的

1. 数乘
2. 加减
3. 乘
4. 下标访问元素
5. 流输入输出
6. 转置

6个功能。

`Matrix.h`

```c++
class Matrix {
private:
	int** elem;
	int col, row;
	
public:
	Matrix();
	Matrix(int _row, int _col);
	~Matrix();

	Matrix operator+(const Matrix&);
	Matrix operator-(const Matrix&);
	Matrix operator*(const int);
	Matrix operator*(const Matrix&);
	friend Matrix transpose(const Matrix&);
	int* operator[](int) const;
	friend ostream& operator<<(ostream&, const Matrix&);
	friend istream& operator>>(istream&, Matrix&);
};
```

`Matrix`类内有成员`elem`，指向一个存放了矩阵元素的二维数组，`elem[a][b]`代表矩阵第a行第b列的元素（**指标从0开始**）；成员`col`和`row`记录了矩阵的行数和列数。

`transpose`函数和重载的运算符实现了矩阵的运算和输入输出功能。其中，重载`operator[]`实现形如`matrix[a][b]`的下标访问只需要返回指向行数组的指针（即重载了第一个`[]`）。

#### 输入格式

第一行包含一个正整数`n`，表示接下来要输入的矩阵个数，矩阵的序号按输入次序从0开始递增。

对每个矩阵，第一行给出两个正整数`r`和`c`，表示这个矩阵的行数和列数，接下来`r`行，每行`c`个整数以空格隔开，表示这个矩阵的元素。

矩阵输入完成后，输入一个正整数`m`，表示操作个数。

接下来`m`行，每行包含一个字符串`op`和若干个参数。

- `op`为`+`时，参数有2个：`opnd1`、`opnd2`，表示将序号为`opnd1`、`opnd2`的两个矩阵相加。
- `op`为`-`时，参数有2个：`opnd1`、`opnd2`，表示用序号为`opnd1`矩阵减去序号为`opnd2`的矩阵。
- `op`为`*`时，参数有2个：`opnd1`、`opnd2`，表示用序号为`opnd1`矩阵左乘序号为`opnd2`的矩阵。
- `op`为`.*`时，参数有2个：`opnd1`、`opnd2`，表示序号为`opnd1`矩阵数乘`opnd2`。
- `op`为`t`时，参数有1个：`opnd1`，表示求序号为`opnd1`矩阵的转置。
- `op`为`[]`时，参数有3个：`opnd1`、`opnd2`、`opnd3`，表示求序号为`opnd1`矩阵的第`opnd2`行、第`opnd3`列的元素。
- `op`为`?`时，参数有1个：`opnd1`，表示求序号为`opnd1`的矩阵。

#### 输出格式

对每个运算符，输出得到的矩阵或元素。每个`r`行`c`列的的矩阵输出`r`行，每行`c`个元素以空格隔开。

#### 输入样例

```
3
3 3
0 8 1
8 6 7
2 3 -1
3 2
5 0
1 -6
9 -10
3 3
1 0 0
0 1 0
0 0 1
7
+ 0 2
- 2 0
* 0 1
.* 2 -6
t 1
[] 1 1 1
? 2
```

#### 输出样例

```
1 8 1 
8 7 7 
2 3 0 
1 -8 -1 
-8 -5 -7 
-2 -3 2 
17 -58 
109 -106 
4 -8 
-6 0 0 
0 -6 0 
0 0 -6 
5 1 9 
0 -6 -10 
-6
1 0 0 
0 1 0 
0 0 1 
```

#### 数据规模和约定

对于100%的数据，有$$2 \leq n \leq 10$$，$$1\leq r,c \leq 30$$，$$1 \leq m \leq 50 $$，所有元素和运算结果都在`int`范围内。

**时间限制：1s**

**空间限制：256MB**

**Comment by hzhwcmhf** [comment]
可以。对于乘法，请写明是矩阵乘法而不是逐元素乘法。然后每个操作都在输入格式部分强调一下参与运算矩阵的维度吧，保证运算合法。

请将完整题面、数据（包括数据生成文件）、judger和答案程序，自行测试通过。完成之后发到邮箱 [huangfei382@163.com](mailto:huangfei382@163.com)。对于编写judger有问题可在小教员群（或找助教）讨论

**Comment by hzhwcmhf** [comment]
验收通过
