### ISSUE TITLE
Proposal （第四次作业，计算几何）

### ISSUE THREAD

**Issue by ren258** [JianGuanTHU/UOJ_Offline#17]
虚函数、多态、向下类型转换、输入输出流重载

<h5> 题目大意 </h5>

题目提供基类 Point 表示二维平面上一点，重载输入输出

```cpp
class Point {                                // 点类
private:
    int x, y;
public:
    Point(int _x, int _y);                  // 表示二维平面内一点
    ~Point();
    friend istream &operator>>(istream &in, Point &P);
    friend ostream &operator<<(ostream &out, const Point &P);
};
```

题目提供抽象基类 Shape 表示一个几何图形，继承自 Point 

```cpp
class Shape: public Point {                 // 形状类，抽象基类
public:
    Shape();
    virtual ~Shape() = 0;
    virtual int area() = 0;                 // 表示面积
    virtual int circum() = 0;               // 表示周长
};
```

需要实现派生类 Rectangle 表示矩形，继承自 Shape

```cpp
class Rectangle: public Shape {             // 矩形类
private:
    Point A, B;                             // 左下角和右上角坐标
public:
    Rectangle(Point _A, Point _B);
    ~Rectangle();
    int area() override;
    int circum() override;
    bool contain(Point P);                  // 判断点是否在矩形中(或边上)
};
```

需要实现派生类 Square 表示正方形，继承自 Rectangle

```cpp
class Square: public Rectangle {            // 正方形类
public:
    Square(Point _A, Point _B);
    ~Square();
};

```

需要实现派生类 Circle 表示圆，继承自 Shape

```cpp
class Circle: public Shape {                // 圆形类
private:
    Point O;                                // 圆心
    int r;                                  // 半径
public:
    int area() override;
    int circum() override;
};
```

额外函数: 

```cpp
Rectangle *init(Point A, Point B);          // 根据 A 和 B 的位置关系生成一个 Rectangle 或 Square 类指针

string getType(Shape *S);                   // 返回一个字符串表示实际类型
```

计划在下发的 .h 中实现构造函数和析构函数，让做题人在 .cpp 中实现其余函数

<h5> 输入格式 </h5>

输入 n 个形状(通过 Point 类输入流)，只知道为 Rectangle 或 Circle ，对 Rectangle 类输入调用 init 函数，用 Shape* 数组存储所有形状

<h5> 输出格式 </h5>

依次查询数组中每个元素的 area, circum, getType，需要与标准输出一致

计划下发不可修改的 main.cpp 与 Makefile

**Comment by ren258** [comment]
为了避免浮点误差，所有坐标和长度均为整数，π 取 3

**Comment by ren258** [comment]
我想把 getType 设置成一个外部函数而不是成员函数，这样是不是就能考察了(就是为了考察向下转换而设计的，但感觉也不是很强行?)

**Comment by hzhwcmhf** [comment]
向下转换一般用于子类接口不一致的情况，目前这个场景太假了，感觉需要再想想

**Comment by ren258** [comment]
那这样能不能考察向下转换
实现一个 string contain(Shape *S, Point *p) 函数，如果 S 是 Rectangle 类就调用 S 的 contain 方法并输入 "true"/"false"，如果 S 是 Circle 就输出 "it's too difficult"
在输入的操作中会加入对 contain 函数的考察

**Comment by hzhwcmhf** [comment]
我觉得不要为了使用某个功能而去构造一个需求，最好去看一下真正的应用里面在什么地方需要向下转换
stackoverflow里有一个讨论可以看下 https://stackoverflow.com/questions/62777666/where-downcasting-is-actually-useful
在我的理解里，一般使用downcasting的场景是：
框架提前实现了对某一个基类的维护操作，其接口都是基类指针。
用户可以通过继承基类，扩展实现自己的子类。同时可以将子类的指针转换为基类指针，送给框架维护。之后如果从框架取得了基类指针，再向下转为子类指针进行操作。

**Comment by ren258** [comment]
emm.. 我本来想的是"假定"实现了一些子类的特有功能(因为感觉特有功能主要考察算法实现而不是oop)，然后就考察向下转换就行了
修改思路: 分别重载每个子类的输出流(在输出流中可以输出一些提示符表示这是哪个类)，将所有对象初始存放在 vector<Shape*> 里，最后通过一个函数将其转换为一个tuple<vector<Rectangle*>, vector<Square*>, vector<Circle*>> 对象，再对这三者分别输出，在这个函数中使用向下转换
或者就不要这个功能了？(因为本来设计的就是对一些 Shape* 进行平等的操作，有点难想到啥需要子类特有操作的地方..)

**Comment by hzhwcmhf** [comment]
我建议对背景做调整。目前这个场景不合适，感觉是将一个简单东西故意写复杂。
题目中的封装一定是要有利于功能实现，推荐借鉴一些设计模式的best practice

**Comment by ren258** [comment]
我上网学习了一下，好像普遍认为 dynamic_cast 并不是一个很好的设计..也并不推荐使用它
来源(他正好也是说 shape 和 circle 类的)：https://www.quora.com/Why-is-dynamic_cast-considered-bad-practice-and-when-is-it-really-needed-C
```text
First what is a dynamic_cast? Better start with what is a cast? A cast is when you have a variable of one type, and you want to see it as a different type. Like you have an integer 3 and you want that as the floating point 3.0f. That's a cast — specifically a static_cast.

A dynamic_cast is when you have a pointer to a type, and you want to see it as a pointer to a particular sub-type. Like say you have a pointer to a Shape, and you want to see that as a pointer to a Circle. Presumably a Circle “is a” Shape, so that makes sense. However, you can't be sure whether this particular Shape happens to be a Circle or not. So a dynamic_cast asks the system to figure out whether it is a Circle or not for you. If it is, C++ will give it to you as a pointer to a Circle.

That's useful. It can get you out of some design traps. Like you have a list of Shapes, but you need to treat Circles differently.

What's wrong with it? Well on the one hand you probably don't need it. Can't you use virtual functions to treat your sub-classes differently?

The other thing is C++ can be compiled with dynamic_cast enabled or disabled. If you enable it, all classes end up getting the Real-Time Type Information (RTTI) added to them. That may be quite a price to have to pay just to get yourself out of a bad design decision that could have been solved with a virtual function.
```
就是说对于结构相似的使用基类指针维护的一系列对象，可以用虚函数的方式来操作子类指针；如果子类真的有特别特殊的功能需要维护，那完全可以不维护基类指针而再单独维护一个子类的对象数组去做这些事情..所以我感觉怎么设计都会有些强行(比如第四次作业第四题在最后计算 PlaceholderNode 的值时用到了向下转换，但我认为可以在主函数生成时就把 PlaceholderNode 单独存成一个数组，就不要再做转换了)
目前想到的一个可能的改法(借鉴自 https://softwareengineering.stackexchange.com/questions/363410/proper-design-to-avoid-the-use-of-dynamic-cast) 是维护一个管理所有 Shape 的类 ShapeManager，包含一个 Shape 数组，在其中实现一些对特定 Shape 操作的函数(比如把把所有 Circle 按比例放大，这确实是这个类的特有功能)，这样在 ShapeManager 中为实现这个功能就必须要用到向下转换了

**Comment by hzhwcmhf** [comment]
我们目前的作业确实有些问题，但如果出新题的话尽量还是要控制质量避免误导以后的同学。

你说的这个情景我觉得还是有些假，如果ShapeManager已知部分Shape是Circle，那么单独存个数组就行。
按我的理解，一般downcasting的情景是：
1. ShapeManager不知道这些Shape具体是什么，但他可以在不知道这些Shape具体子类是什么的情况下做一些操作，比如做一些维护顺序、数量之类。
2. 如果我们需要增加某个子类，比如Circle。那么应该有一段外部调用，他既使用ShapeManager原本的功能，同时也需要Circle的新功能。但ShapeManager只支持Shape，所以给ShapeManager时只传入Shape，之后使用时，外部代码会再从Shape转换为Circle。
3. 最好不要把dynamic_cast当做判断类型的方法，这种操作一般不是比较好的设计模式

再换个例子，如果我们不用模板实现vector，那么也需要downcasting。假设所有元素都是object的子类，vector维护的数组也是object。那么在访问vector第k个元素后，返回的是object，但我们只有把他转换回原来的类别，才能调用原来的方法。这时候downcasting才是必须的

**Comment by hzhwcmhf** [comment]
不把某一个子类单独存下来的原因是

1. 某些功能需要对所有元素进行统一操作，比如队列调度、事件触发等，分开以后实现不了
2. 框架是提前写好的，子类是后来增加的。类比vector和其储存的元素，储存元素可以在vector固定之后新增

所以如果一定要设计downcasting，需要有个合适的场景。目前Shape和Circle的背景下，我也想不出来有什么合适的理由不能拆开维护

**Comment by ren258** [comment]
好吧我要不我还是重新出一个题吧..

**Comment by ren258** [comment]
目前重新想了一个题，不知道会不会太偏，所以先说一下大致想法？(灵感来源自第六次作业第三题的正则表达式)
实现一个 Json 类，支持对 json 数据的读取和存储，计划要求实现以下函数：
json.loads(str): 将一个 c++ 字符串转成 json 对象，考察正则表达式和字符串处理
json.dumps(): 将一个 json 对象转成一个  c++ 字符串，考察字符串处理
json.print(indent): 打印一个 json 对象(像 python 那样打印)，indent 为缩进

目前想到的实现策略是在 Json 类中存一个 Json** 表示指向子成分的指针的数组，所有操作都从外层向内层递归进行，应该会简单一些，这样也算是用到了其他 oop 的知识？暂时还没想到更简单的实现策略

**Comment by ren258** [comment]
目前重新想了一个题，不知道会不会太偏，所以先说一下大致想法？(灵感来源自第六次作业第三题的正则表达式)
实现一个 Json 类，支持对 json 数据的读取和存储，计划要求实现以下函数：
json.loads(str): 将一个 c++ 字符串转成 json 对象，考察正则表达式和字符串处理
json.dumps(): 将一个 json 对象转成一个 c++ 字符串，考察字符串处理
json.print(indent): 打印一个 json 对象(像 python 那样打印)，indent 为缩进

数据分为两种：输入字符串输出 json ，输入 json 输出字符串 (如果再难的话还可以加入修改？)

目前想到的实现策略是在 Json 类中存一个 Json** 表示指向子成分的指针的数组，所有操作都从外层向内层递归进行，应该会简单一些，这样也算是用到了其他 oop 的知识？暂时还没想到更简单的实现策略

**Comment by ren258** [comment]
目前重新想了一个题，不知道会不会太偏，所以先说一下大致想法？(灵感来源自第六次作业第三题的正则表达式)
实现一个 Json 类，支持对 json 数据的读取和存储，计划要求实现以下函数：
json.loads(str): 将一个 c++ 字符串转成 json 对象，考察正则表达式和字符串处理，需要进行格式检查，非法格式需要报错
json.dumps(): 将一个 json 对象转成一个 c++ 字符串，考察字符串处理
json.print(indent): 打印一个 json 对象(像 python 那样打印)，indent 为缩进

数据分为两种：输入字符串输出 json ，输入 json 输出字符串 (如果再难的话还可以加入修改？)

目前想到的实现策略是在 Json 类中存一个 Json** 表示指向子成分的指针的数组，所有操作都从外层向内层递归进行，应该会简单一些，这样也算是用到了其他 oop 的知识？暂时还没想到更简单的实现策略

**Comment by ren258** [comment]
目前重新想了一个题，不知道会不会太偏，所以先说一下大致想法？(灵感来源自第六次作业第三题的正则表达式)
实现一个 Json 类，支持对 json 数据的读取和存储，计划要求实现以下函数：
json.loads(str): 将一个 c++ 字符串转成 json 对象，考察正则表达式和字符串处理，需要进行格式检查，非法格式需要报错
json.dumps(): 将一个 json 对象转成一个 c++ 字符串，考察字符串处理
json.print(indent=4): 打印一个 json 对象(像 python 那样打印)，indent 为缩进

数据分为两种：输入字符串输出 json ，输入 json 输出字符串 (如果再难的话还可以加入修改？)

目前想到的实现策略是在 Json 类中存一个 Json** 表示指向子成分的指针的数组，所有操作都从外层向内层递归进行，应该会简单一些，这样也算是用到了其他 oop 的知识？暂时还没想到更简单的实现策略

**Comment by hzhwcmhf** [comment]
大致可以，你另开个issue吧。注意要限制一下json字符串的内容，显示的说明一下格式和可能包含的字符是什么样的，弄一个简化版的就可以，不用支持所有功能
