### ISSUE TITLE
Proposal（第二次作业，空中管制）

### ISSUE THREAD

**Issue by nine-point-eight-p** [JianGuanTHU/UOJ_Offline#27]
### 题目描述

我们来模拟一个进行空中管制的塔台的工作。这里主要有两类对象：plane和tower。以下是一些说明。

* plane：顾名思义，即飞机。飞机主要有两类属性：

  * 航班号：字符串类型，每一架飞机都拥有一个唯一的航班号。

  * 飞行状态：由位置和速度两部分构成。由于塔台使用雷达，所以飞机的位置采用柱坐标系，即平面极坐标系（距离，角度）加上高度。平常巡航时，飞机是平飞的（显然），所以这里的速度仅仅是指投影到水平面上的移动速度，它包括速度的大小和速度的方向。以上数据均采用`double`类型。

    距离的单位是海里，角度采用角度制（以x轴为0度，逆时针方向至360度），高度的单位是英尺，速度的单位是海里/小时。

  plane的主要功能有：

  * 更新（水平）位置：根据速度大小和方向更新（水平）位置。

  * 更改属性：能够更改高度/速度大小/速度方向。更改时，将设定要达到的高度/速度大小/速度方向。

    高度的变化率为60英尺/秒^2，速度大小的变化率是1海里/秒^2，速度方向变化率为2角度/秒。

  * 输出信息：输出飞机航班号、所在位置及速度。

* tower：塔台。主要属性为“范围”，即其所管辖的空域半径，`double`类型。主要的功能有

  * 增加：根据指令将飞机加入管理列表。
  * 删除：飞机飞出管辖空域时将其移出管理列表。
  * 安全检查：当任两架飞机的水平距离小于3海里且垂直距离小于1000英尺时，判定为危险情况。
  * 访问：通过以航班号为下标获取飞机信息，*若无相应飞机，返回距离塔台最近的飞机*。
  * 输出信息：按到塔台的距离从小到大的顺序输出所有飞机的信息。
  * 其余详见main.cpp。

我们将模拟一段时间内的管制过程，以1秒为单位时间（tick）进行。在每个tick中，先处理飞机高度/速度大小/速度方向的变化，再处理（水平）位置的更新。

请参考main.cpp，编写plane.h和tower.h。

```c++
// main.cpp
#include "plane.h"
#include "tower.h"
#include <iostream>

int main()
{
    double range;
    std::cin >> range;
    Tower tower(range);

    bool running = true;
    int cmd_num, tick = 0;
    std::cin >> cmd_num;
    while (cmd_num--)
    {
        int cur_time;
        std::cin >> cur_time;
        while (tick < cur_time) // Update the time
        {
            tower.update();
            if (tower.safety_check() == false)
            {
                running = false;
                break;
            }
            ++tick;
        }
        if (!running)
            break;

        int opr;
        char name[10] = {};
        std::cin >> opr >> name;
        if (opr == 0) // New plane
        {
            double dist, angle;
            int alt, spd, head;
            char dest[10] = {};
            std::cin >> dist >> angle >> alt >> spd >> head >> dest;
            tower.addPlane(Plane(name, dist, angle, alt, spd, head));
        }
        else if (opr == 1) // Set altitude
        {
            int alt;
            std::cin >> alt;
            tower[name].setAltitude(alt);
        }
        else if (opr == 2) // Set speed
        {
            int spd;
            std::cin >> spd;
            tower[name].setSpeed(spd);
        }
        else if (opr == 3) // Set heading
        {
            int head;
            std::cin >> head;
            tower[name].setHeading(head);
        }
        else if (opr == 4) // Print a plane's information
        {
            tower[name].printInfo();
        }
        else if (opr == 5) // Print all information
        {
            tower.printAllInfo();
        }
        else
        {
            std::cout << "Invalid operation" << std::endl;
        }
    }

    if (running)
        std::cout << "Safe" << std::endl;
    else
        std::cout << "Game over" << std::endl;
    return 0;
}
```

### 备注

* 知识点：普普通通的封装、（很少的）运算符重载
* 个人认为背景可能略显复杂，但本质上也只是一些在坐标系下的位移、速度的基本运算。单位并不是很重要，只需要进行数据运算。
* 飞机的那三种属性可能会显得冗余。可以去掉一两个。
* 可以想办法揉进去更多的运算符重载。

**Comment by hzhwcmhf** [comment]
基本可行。可以考虑重载plain和tower的输出
另外请注意输出可能存在精度问题，需要使用合适的checker或者合适的精度，这部分麻烦描述一下

**Comment by nine-point-eight-p** [comment]
好的，那就加上两个输出的重载。

数据类型做一点修正：飞机的高度/速度大小/速度方向其实均为整数。不过距离和角度（即水平坐标）似乎无法避免浮点数的出现。也许能控制在1e-6？

还有一个考虑是：不知道极坐标的这些运算是否过于复杂。如有需要也可以换为直角坐标系（但是有些怪，而且需要计算的东西应该也不会变少，只是可能更熟悉）

**Comment by hzhwcmhf** [comment]
极坐标还行，不算太复杂。我比较关心的是精度问题，主要是不同的实现方式可能相差很小，但输出会不一致。比如2.999和3.001转成int，一个是2、一个是3。
一个解决方案是，你在出数据的时候控制浮点数的范围。比如取四舍五入2位小数后答案是1.00，那么真正答案应该保持在0.998-1.002之间，这样不至于说不同实现输出不同
另一种解决方案是使用特殊的checker，参考./builtin/rncmp，或者在基础上做修改。
你先看看哪种比较容易？

**Comment by nine-point-eight-p** [comment]
额，我好像还不是太理解。第一种方案是说，提高输入精度，放低输出精度要求么？第二种的话，我看了一下但是没太看懂（也不是很懂judger怎么弄……），如果要修改的话，是去更改EPS这个误差限制么？还烦请您再解释一下。

**Comment by nine-point-eight-p** [comment]
似乎明白了。我觉得可以试试第二种。自己写判断的话，应该是只用写那个cpp就可以了吧？如果有一些特殊的判断方法（比如我打算把第一个字符是不是数字当作判断是否为浮点数的标准），应该也没问题吧？

**Comment by hzhwcmhf** [comment]
> 如果有一些特殊的判断方法（比如我打算把第一个字符是不是数字当作判断是否为浮点数的标准），应该也没问题吧？
只要符合你的输出即可

也不一定用cpp，使用python也可以，只要cmd参数、返回值、输出是类似的就行

**Comment by nine-point-eight-p** [comment]
好的，那我就试着写一个自己的checker吧

**Comment by nine-point-eight-p** [comment]
额，这里好像还有一个快被遗忘的题目……还需要补充些什么吗（样例输入输出正在做）

**Comment by nine-point-eight-p** [comment]
### 题目描述

我们来模拟一个进行空中管制的塔台的工作（~~进行了很多魔改~~）。我们将模拟一段时间内的管制过程，以1秒为单位时间（tick）进行。这里主要有两类对象：plane和tower。以下是一些说明。

* plane：顾名思义，即飞机。飞机主要有两类属性：

  * 航班号：字符串类型，每一架飞机都拥有一个唯一的航班号。

  * 飞行状态：由位置和速度两部分构成。由于塔台使用雷达，所以飞机的位置采用柱坐标系，即平面极坐标系（距离，角度）加上高度。平常巡航时，飞机是平飞的（显然），所以这里的速度仅仅是指投影到水平面上的移动速度，它包括速度的大小和速度的方向。以上数据均采用`double`类型。

    距离的单位是海里，角度采用角度制（以x轴为0度，逆时针方向至360度），高度的单位是英尺，速度的单位是海里/小时。

  plane的主要功能有：

  * 更新（水平）位置：根据速度大小和方向更新（水平）位置。在每个tick中，我们认为（水平）速度不变，即水平投影做匀速运动。

  * 更改属性：能够更改高度/速度大小/速度方向。更改时，将设定要达到的高度/速度大小/速度方向。

    高度的变化率为60英尺/秒^2，速度大小的变化率是1海里/秒^2，速度方向变化率为2角度/秒^2。

  * 输出信息：输出飞机航班号、所在位置及速度。

* tower：塔台。主要属性为“范围”，即其所管辖的空域半径，`double`类型。主要的功能有

  * 增加：根据指令将飞机加入管理列表。
  * 删除：飞机飞出管辖空域时将其移出管理列表。
  * 安全检查：当任两架飞机的水平距离小于3海里且垂直距离小于1000英尺时，判定为危险情况。两个tick之间的时间不用考虑（假装雷达正在扫描中）。
  * 访问：通过以航班号为下标获取飞机信息，*若无相应飞机，返回距离塔台最近的飞机*。
  * 输出信息：按到塔台的距离从小到大的顺序输出所有飞机的信息。
  * 其余详见main.cpp。

在每个tick中，**先处理飞机高度/速度大小/速度方向的变化，再处理（水平）位置的更新。**

请参考main.cpp，编写plane.h和tower.h。

```c++
// main.cpp
#include "plane.h"
#include "tower.h"
#include <iostream>

using std::cin;
using std::cout;
using std::endl;

int main()
{
    double range;
    cin >> range;
    Tower tower(range);

    bool running = true;
    int cmd_num, tick = 0;
    cin >> cmd_num;
    while (cmd_num--)
    {
        int cur_time;
        cin >> cur_time;
        while (tick < cur_time) // Update the time
        {
            tower.update();
            if (tower.safety_check() == false)
            {
                running = false;
                break;
            }
            ++tick;
        }
        if (!running)
            break;

        int opr;
        char name[10] = {};
        cin >> opr;
        cout << opr << endl;
        if (opr == 0) // New plane
        {
            double dist, angle;
            int alt, spd, head;
            cin >> name >> dist >> angle >> alt >> spd >> head;
            tower.addPlane(Plane(name, dist, angle, alt, spd, head));
        }
        else if (opr == 1) // Set altitude
        {
            int alt;
            cin >> name >> alt;
            tower[name].setAltitude(alt);
        }
        else if (opr == 2) // Set speed
        {
            int spd;
            cin >> name >> spd;
            tower[name].setSpeed(spd);
        }
        else if (opr == 3) // Set heading
        {
            int head;
            cin >> name >> head;
            tower[name].setHeading(head);
        }
        else if (opr == 4) // Print a plane's information
        {
            cin >> name;
            cout << tower[name];
        }
        else if (opr == 5) // Print all information
        {
            cout << tower;
        }
        else
        {
            cout << "Invalid operation" << endl;
        }
    }

    if (running)
        cout << "Safe" << endl;
    else
        cout << "Game over" << endl;
    return 0;
}
```

### 样例输入

（正在做）

### 样例输出

（正在做）

**Comment by hzhwcmhf** [comment]
请将完整题面、数据（包括数据生成文件）、judger和答案程序，自行测试通过。完成之后发到邮箱 [huangfei382@163.com](mailto:huangfei382@163.com)。对于编写judger有问题可在小教员群（或找助教）讨论。

数据请至少有一个测试点是样例，便于同学查错
