### ISSUE TITLE
Proposal（第二次作业，向量运算库）

### ISSUE THREAD

**Issue by TRCYX** [JianGuanTHU/UOJ_Offline#3]
给定 `main.cpp`，要求实现表示 3 维浮点数向量的类 `Vec3`，从下列操作中选择一些有代表性或能提高完成度的支持：
- 加、（取正）、取负、减
-（双方向的）数乘、数除
- 对应的复合赋值
- 取下标
- `==` 、`!=`
- 用 `operator bool` 和 `!` 判断是否为 `0`
- 内积、叉积
- 范围 `for` 循环遍历
- `iostream` 输入输出

另外可以要求考察操作对 `this` `const` 和非 `const` 的区分，如下标和复合赋值操作会受到影响。

此题考察的知识点是典型的带有运算符重载的 C++ 类实现，可以展示不可变性在 C++ 中的使用、不同运算间的代码复用等。

**Comment by TRCYX** [comment]
内积、叉积等可能会在 `main.cpp` 中用到的函数可以作为下发文件在头文件中提供。

**Comment by liangrz15** [comment]
需要细化一下题目。建议如下：
1. 鉴于*DMFB液滴管理系统*较多地考察运算符重载，本题最好不要把运算符重载作为主要考察点；
2. 可以通过Vec3类考察构造函数、复制构造函数；
3. 可以考察操作对 `this` `const` 和非 `const` 的区分;
4. 没有明确考察点的操作可以不用支持，比如点积、叉积;
5. 目前还没有讲到范围`for`循环遍历，不要考察这一点。

**Comment by TRCYX** [comment]
感谢您审核。不过这个场景的主要考察内容的确就是运算符重载，不太适合改变。例如这样的类的非自动生成的构造函数意义不大。如果要重点考察其他知识点，我觉得不妨另取别的场景。望助教能够再考虑考虑。

**Comment by liangrz15** [comment]
同意你的说法。我撤回我的第1点建议，以及第2条建议中对复制构造函数的考察（因为还没讲到）。
如果需要替代作业的话，需要更加完善题目，并再出一道选择题。
