### ISSUE TITLE
Proposal （第六次作业，人生重开模拟器）

### ISSUE THREAD

**Issue by Fuyuky** [JianGuanTHU/UOJ_Offline#31]
### 考点

模板、继承、多态、虚函数重载、函数指针

### 题目大意

装饰器模式是一种设计模式，可以在不定义新的类的情况下扩展对象的功能。

上学期初有一款爆火的游戏叫《人生重开模拟器》，现在你要实现这款游戏的简化版。

在简化版游戏中，每个人会有 财富、快乐 两种属性。

随着年龄增长，每一年都会遇到某个事件，例如：

宫崎英矮发布了售价 x 的新游戏：财富减少 x，快乐增加 x

上司宣布执行 996 工作制：快乐减半，财富增加等同于快乐减少量的两倍

等等等等

经过你的观察，这些事件分为两种（设事件发生前财富为 $x$，快乐为 $y$）：

`Spend_wealth(f,g)` ：财富减少 $f(x)$，快乐增加 $g(x)$。

`Spend_joy(f,g)`：财富增加 $f(y)$，快乐减少 $g(y)$。

其中 $f,g$ 都是给定的，形如 `int(int)` 的函数。

你至少需要实现 `Human`，`After_spending_wealth`，`After_spending_joy` 三个类，其中后两个类继承自 `Human`。

`main.cpp` 中实现了 `Spend_wealth(f,g)` 和 `Spend_joy(f,g)` 的功能。

例如对于一个 `Human*` 类的实例 `x`，`Spend_wealth(f,g)` 表示为 `x=new After_spending_wealth(x,f,g)`

`Human` 中还需实现一个函数 `life_review`，以输出目前经历过的所有事件，形如：`在 i 年获得了 x 点财富，失去了 y 点快乐`。

（利用装饰器模式来实现对类中变量和成员函数的修改）

（因为刚刚一直上不去 github 所以提交超时了）

**Comment by hzhwcmhf** [comment]
基本可行。可以给一下Human的实现吗？

**Comment by hzhwcmhf** [comment]
因没有后续更新取消
