### ISSUE TITLE
Proposal （第4次作业 函数计算器)

### ISSUE THREAD

**Issue by Ksitta** [JianGuanTHU/UOJ_Offline#9]
## 题目描述

小明在计算函数值时发现很多函数都可以使用C++来实现，而math.h头文件中提供了大量实用的数学函数，在做数学题的他想偷偷懒，于是编写了一个函数类，并且实现了一个指数函数类。他现在又想偷懒了，于是找到了你，希望你完善一次函数、组合函数、复合函数的实现。

代码拆分、完整代码会在Proposal通过后进行编写（逃

## 部分代码

main.cpp

主要用于测试三个类实现的正确性，以及是否补充了基类的虚析构函数，从而防止内存泄露

Function.h

```
#pragma once
#include <vector>
#include <cmath>

class Function{
public:
    Function() {}
    void getRange(double start, double finish, double step, std::vector<double> data){
        for(double pos = start; pos <= finish; pos += step){
            data.push_back(getPoint(pos));
        }
    }
    virtual double getPoint(double point);
    // Todo
};

// Todo
// 请参照指数函数类(ExponentialFunction)实现一个一次函数类并且补充完整下列的复合函数以及组合函数类
// 复合函数即f(g(x))
// 组合函数即a * f(x) + b * g(x) 形式
// 并且要求，传入的参数的析构在该类被析构时同时析构
// 即补充完整Function类

class LinnerFunction : public Function{

};

class ExponentialFunction : public Function{
private:
    double _base;
public:
    ExponentialFunction(double base) : _base(base) {}
    double getPoint(double point){
        return powl(_base, point);
    }
};

class CombinationFunction : public Function{
private:
    Function *_func_1;     // function 1, denoted as f
    Function *_func_2;     // function 1, denoted as g
    double _coefficient_1; // coefficient 1, denoted as a
    double _coefficient_2; // coefficient 1, denoted as b
public:
    CombinationFunction(Function *fun_1, Function *fun_2, double coe_1, double coe_2) 
    : _func_1(fun_1), _func_2(fun_2), _coefficient_1(coe_1), _coefficient_2(coe_2) {}
    // compute a * f(x) + b * g(x)
    // Todo
};

class CompositeFunction : public Function{
private:
    Function *_outer; // function 1, denoted as f
    Function *_inner; // function 1, denoted as g
public:
    CompositeFunction(Function *outer, Function* inner)
    : _outer(outer), _inner(inner) {}
    // compute f(g(x))
    // Todo
};
```

## 考察知识点

虚函数、析构函数

**Comment by Ksitta** [comment]
### 题目描述

小明在计算函数值时发现很多函数都可以使用C++来实现，而cmath头文件中提供了大量实用的数学函数，在做数学题的他想偷偷懒，于是编写了一个函数类，并且自己实现了一个指数函数类。他现在又想偷懒了，于是找到了你，希望你完善一次函数、组合函数、复合函数的实现。

文件下载地址：[下载链接]

### 输入样例

第一行包括一个正整数 $n$

后面会跟相应的函数构造

对于$n$的解释如下

0代表构造常值函数后面会跟一个浮点数 c，如：

```
0
1.5
```

表示构造了一个

$f(x)=1.5$这样的常量（ConstFunc）函数

1代表构造线性函数，后面会跟两个浮点数a b表示构造一个y=ax+b这样的函数，如：

```
1
3.3 1.2
```

构造了一个$f(x)=3.3x + 1.2$这样的线性（LinnerFunc）函数

2代表构造指数函数，后面会跟一个浮点数b表示构造一个y=b^x这样的函数，如：

```
2 
2.5
```

构造了一个$f(x)=2.5^x$这样的指数（ExpFunc）函数

3代表构造一个复合函数。后面会跟两组构造（这个构造过程可能是递归的，复合函数再复合）

先构造内层函数$g(x)$，再构造外层函数$f(x)$

如：

```
3
2
1.2
1
1.6 2.5
```

其中

```
2
1.2
```

表示构造了一个$g(x)=1.2^x$这样的指数函数

```
1
1.6 2.5
```

表示构造了一个$f(x)=1.6x+2.5$这样的线性函数

复合起来就是 $f(g(x))=1.6\times1.2^x+2.5$

4代表构造一个组合函数，下面会跟两个浮点数a, b

```
4
3.3 4.4 // a b
2       // 指数函数
1.2     // f(x) = 1.2^x
0       // 常值函数
1.6     // g(x) = 1.6
```

得到的函数就是 $h(x)=a \cdot f(x) + b \cdot g(x)$ 

这个例子中为$h(x)=3.3\times1.2^x+4.4\times1.6$

接下来有一个正整数m，表示有m个点需要求这个函数的函数值，接下来一行有m个浮点数

```
4
0.1 2.2 3.3 4.4
```

虽然有这么多个不同的构造，你会发现实际上我们得到了一个函数

它可能由多个函数复合或组合起来而成

你可以看下面的例子

### 样例1

**输入**

```
1
1.2
3.3
4
0 1.1 2.2 3.3
```

这里构造了一个线性函数$f(x)=1.2x+3.3$

有4个测试点

0 1.1 2.2 3.3

**输出**

结果已经自动保留了5位小数

```
3.30000
4.62000
5.94000
7.26000
YES
```

最后一行YES代表代码会检测你的程序不存在内存泄露，如果存在则会输出NO

### 样例2

**输入**

```
3
3
1
1.2 3.3
2
5.2
1
1.6 2.8
3
1.1 2.2 3.3
```

样例解释：

这个样例构造了一个经过两次复合得到的函数

第一行3表示最终我们要的函数我们记作 $h(x)$，他由$f(x)$和$g(x)$复合而成，$h(x)=f(g(x)) $

第二行表示我们构造内层的函数g(x)，他是一个复合函数由下面4行的函数复合而成

记$g(x) = u(w(x))$

第3、4行构造了一个线性函数$w(x)=1.2x+3.3$

第5、6行构造了一个指数函数$u(x)=5.2^x$

复合得到的结果即$g(x)=u(w(x))=5.2^{1.2x+3.3}$

第7、8行构造了一个线性函数$f(x)=1.6x+2.8$

最外层复合的结果即为$f(g(x)) = 1.6 \times ( 5.2 ^{1.2 x+3.3}) + 2.8$

最终3个测试点为1.1 2.2 3.3

**输出**

```
3254.08792
28656.44288
252527.72887
YES
```

### 要求

1. 不修改 `main.cpp` `expfunc.h` `constfunc.h`。
2. 如果你增加了其他的.cpp文件请相应修改Makefile

### 限制与约定

计算过程中结果不会超出double能表示的范围

**时间限制：1s**

**空间限制：256MB**

### 提交格式

根据提供的压缩包内的内容，补充相应的代码（ CompFunc 类，Day 类，Friday 类）。你应该将你的文件打包成一个zip压缩包并上传。评测时，OJ会将提供的 `main.cpp` `constfunc.h` `expfunc.h`贴入你的目录下进行编译并执行。

### 评分标准

OJ评分占100%

**Comment by Ksitta** [comment]
main.cpp
```
#include <iostream>
#include <vector>
#include <iomanip>

#include "func.h"
#include "constfunc.h"
#include "linnerfunc.h"
#include "expfunc.h"
#include "compfunc.h"
#include "combfunc.h"

using namespace std;

Func *create_const();
Func *create_linner();
Func *create_exp();
Func *create_comp();
Func *create_comb();
Func *choice(int);

int main(){
    int n, m;
    Func * functions;
    cin >> n;
    functions = choice(n);
    cin >> m;
    for(int i = 0; i < m; i++){
        double test_point;
        cin >> test_point;
        cout << setiosflags(ios::fixed) << setprecision(5) << functions->getPoint(test_point) << endl;
    }
    delete functions;
    ConstFunc::checkMemoryLeak();
    return 0;
}

Func *create_const(){
    double c;
    cin >> c;
    return new ConstFunc(c);
}

Func *create_linner(){
    double a, b;
    cin >> a >> b;
    return new LinnerFunc(a, b);
}

Func *create_exp(){
    double base;
    cin >> base;
    return new ExpFunc(base);
}

Func *create_comp(){
    int k;
    cin >> k;
    Func *g = choice(k);
    cin >> k;
    Func *f = choice(k);
    return new CompFunc(f, g);
}


Func *create_comb(){
    double a, b;
    int k;
    cin >> a >> b;
    cin >> k;
    Func *f1 = choice(k);
    cin >> k;
    Func *f2 = choice(k);
    return new CombFunc(f1, f2, a, b);
}

Func * choice(int k){
    if(k == 0){ return create_const(); }
    if(k == 1){ return create_linner(); }
    if(k == 2){ return create_exp(); }
    if(k == 3){ return create_comp(); }
    if(k == 4){ return create_comb(); }
    return nullptr;
}
```c++

**Comment by hzhwcmhf** [comment]
有几处typo：
`LinnerFunc` -> `LinearFunc`
`补充相应的代码（ CompFunc 类，Day 类，Friday 类）`

其他的没问题。题目出完以后发送题面(markdown格式）、数据、judger、标程到huangfei382@163.com。

**Comment by hzhwcmhf** [comment]
题面需要稍微描述一下已经提供的接口，比如说几个类的构造参数、getPoint函数的输入和返回值分别是什么。请直接在这个issue里进行修改

**Comment by Ksitta** [comment]
## 增加部分

小明为你提供了一个不太完整的Function基类，对于每一个子类来说，我们都应该为他实现一个`double getPoint(double)`函数，即输入一个横坐标值(double类型)，返回该点的函数值(double类型)。

```
class Function{
public:
    Function() {}
    void getRange(double start, double finish, double step, std::vector<double> data){
        for(double pos = start; pos <= finish; pos += step){
            data.push_back(getPoint(pos));
        }
    }
    virtual double getPoint(double point);
    // Todo
};
```

比如:

子类LinearFunc实现的是一个线性函数

y=1.1x+2.2那么调用getPoint(2.0);

得到的返回值应该为4.4


main.cpp中已经实现了根据输入调用每个类的构造函数

其中会按照以下参数调用每个类的构造函数，参数传入的顺序是固定的，你可以按照自己的习惯修改相应.h文件中的形参名。

常值函数(已实现)：

```
ConstFunc(double n);
```

传入一double型变量n，构造一个y=n的常值函数

```
LinnerFunc(double a, double b);
```

传入double类型的a, b，构造一个y=ax+b的线性函数

指数函数(已实现)：

```
ExpFunc(double base);
```

传入double类型的base，构造一个y=base^x的指数函数

复合函数

```
CompFunc(Func *outer, Func* inner);
```

传入Func指针outer和inner，分别为已经实现的两个函数

outer为外层函数，inner为内层函数

如我们希望构造h = f(g(x))，则会调用CompFunc(f, g);

组合函数

```
CombFunc(Func *fun_1, Func *fun_2, double coe_1, double coe_2);
```

传入Func指针fun_1和fun_2，以及两个double参数coe_1，coe_2

如我们希望构造h(x) = a\*f(x)+b\*g(x)会调用CombFunc(f, g, a, b);



##完整题面

### 题目描述

小明在计算函数值时发现很多函数都可以使用C++来实现，而cmath头文件中提供了大量实用的数学函数，在做数学题的他想偷偷懒，于是编写了一个函数类，并且自己实现了一个指数函数类。他现在又想偷懒了，于是找到了你，希望你完善一次函数、组合函数、复合函数的实现。

文件下载地址：[下载链接](/download.php?type=problem&id=100)

小明为你提供了一个不太完整的Function基类，对于每一个子类来说，我们都应该为他实现一个`double getPoint(double)`函数，即输入一个横坐标值(double类型)，返回该点的函数值(double类型)。

```
class Function{
public:
    Function() {}
    void getRange(double start, double finish, double step, std::vector<double> data){
        for(double pos = start; pos <= finish; pos += step){
            data.push_back(getPoint(pos));
        }
    }
    virtual double getPoint(double point);
    // Todo
};
```

比如:

子类LinearFunc实现的是一个线性函数

y=1.1x+2.2那么调用getPoint(2.0);

得到的返回值应该为4.4



main.cpp中已经实现了根据输入调用每个类的构造函数

其中会按照以下参数调用每个类的构造函数，参数传入的顺序是固定的，你可以按照自己的习惯修改相应.h文件中的形参名。

常值函数(已实现)：

```
ConstFunc(double n);
```

传入一double型变量n，构造一个y=n的常值函数

```
LinnerFunc(double a, double b);
```

传入double类型的a, b，构造一个y=ax+b的线性函数

指数函数(已实现)：

```
ExpFunc(double base);
```

传入double类型的base，构造一个y=base^x的指数函数

复合函数

```
CompFunc(Func *outer, Func* inner)
```

传入Func指针outer和inner，分别为已经实现的两个函数

outer为外层函数，inner为内层函数

如我们希望构造h = f(g(x))，则会调用CompFunc(f, g)

组合函数

```
CombFunc(Func *fun_1, Func *fun_2, double coe_1, double coe_2) 
```

传入Func指针fun_1和fun_2，以及两个double参数coe_1，coe_2

如我们希望构造h(x) = a\*f(x)+b\*g(x)会调用CombFunc(f, g, a, b) 

### 输入样例

第一行包括一个正整数 $n$

后面会跟相应的函数构造

对于$n$的解释如下

0代表构造常值函数后面会跟一个浮点数 c，如：

```
0
1.5
```

表示构造了一个

$f(x)=1.5$这样的常量（ConstFunc）函数

1代表构造线性函数，后面会跟两个浮点数a b表示构造一个y=ax+b这样的函数，如：

```
1
3.3 1.2
```

构造了一个$f(x)=3.3x + 1.2$这样的线性（LinearFunc）函数

2代表构造指数函数，后面会跟一个浮点数b表示构造一个y=b^x这样的函数，如：

```
2 
2.5
```

构造了一个$f(x)=2.5^x$这样的指数（ExpFunc）函数

3代表构造一个复合函数。后面会跟两组构造（这个构造过程可能是递归的，复合函数再复合）

先构造内层函数$g(x)$，再构造外层函数$f(x)$

如：

```
3
2
1.2
1
1.6 2.5
```

其中

```
2
1.2
```

表示构造了一个$g(x)=1.2^x$这样的指数函数

```
1
1.6 2.5
```

表示构造了一个$f(x)=1.6x+2.5$这样的线性函数

复合起来就是 $f(g(x))=1.6\times1.2^x+2.5$

4代表构造一个组合函数，下面会跟两个浮点数a, b

```
4
3.3 4.4 // a b
2       // 指数函数
1.2     // f(x) = 1.2^x
0       // 常值函数
1.6     // g(x) = 1.6
```

得到的函数就是 $h(x)=a \cdot f(x) + b \cdot g(x)$ 

这个例子中为$h(x)=3.3\times1.2^x+4.4\times1.6$

接下来有一个正整数m，表示有m个点需要求这个函数的函数值，接下来一行有m个浮点数

```
4
0.1 2.2 3.3 4.4
```

虽然有这么多个不同的构造，你会发现实际上我们得到了一个函数

它可能由多个函数复合或组合起来而成

你可以看下面的例子

### 样例1

**输入**

```
1
1.2
3.3
4
0 1.1 2.2 3.3
```

这里构造了一个线性函数$f(x)=1.2x+3.3$

有4个测试点

0 1.1 2.2 3.3

**输出**

结果已经自动保留了5位小数

```
3.30000
4.62000
5.94000
7.26000
YES
```

最后一行YES代表代码会检测你的程序不存在内存泄露，如果存在则会输出NO

### 样例2

**输入**

```
3
3
1
1.2 3.3
2
5.2
1
1.6 2.8
3
1.1 2.2 3.3
```

样例解释：

这个样例构造了一个经过两次复合得到的函数

第一行3表示最终我们要的函数我们记作 $h(x)$，他由$f(x)$和$g(x)$复合而成，$h(x)=f(g(x)) $

第二行表示我们构造内层的函数g(x)，他是一个复合函数由下面4行的函数复合而成

记$g(x) = u(w(x))$

第3、4行构造了一个线性函数$w(x)=1.2x+3.3$

第5、6行构造了一个指数函数$u(x)=5.2^x$

复合得到的结果即$g(x)=u(w(x))=5.2^{1.2x+3.3}$

第7、8行构造了一个线性函数$f(x)=1.6x+2.8$

最外层复合的结果即为$f(g(x)) = 1.6 \times ( 5.2 ^{1.2 x+3.3}) + 2.8$

最终3个测试点为1.1 2.2 3.3

**输出**

```
3254.08792
28656.44288
252527.72887
YES
```

### 要求

1. 不修改 `main.cpp` `expfunc.h` `constfunc.h`。
2. 如果你增加了其他的.cpp文件请相应修改Makefile
3. 补充完整`combfunc.h` `compfunc.h` `func.h` `linearfunc.h` 
4. 防止出现内存泄漏，否则答案也将视为错误

### 限制与约定

计算过程中结果不会超出double能表示的范围

**时间限制：1s**

**空间限制：256MB**

### 提交格式

根据提供的压缩包内的内容，补充相应的代码（ `combfunc.h` `compfunc.h` `func.h` `linearfunc.h`）。你应该将你的文件打包成一个zip压缩包并上传。评测时，OJ会将提供的 `main.cpp` `constfunc.h` `expfunc.h`贴入你的目录下进行编译并执行。

### 评分标准

OJ评分占100%

**Comment by hzhwcmhf** [comment]
验收通过
